spring:
  application:
    name: user-service
  basic:
    enable: false
  ldap:
    urls: ldap://localhost:389
    base: dc=library,dc=com
    username: uid=admin,ou=system
    password: secret


server:
  port: 8081

